version: "3"
services:
  master:
    image: jenkins-master:latest
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    image: jenkins-nginx:latest
    ports:
      - "80:80"
    networks:
      - jenkins-net
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
